// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Scoracle"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns API name, version, status, and available optimizations.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "API root info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/device": {
            "post": {
                "description": "Creates a new anonymous user and returns an access + refresh token pair. First launch only; later launches use /auth/refresh.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register device (anonymous)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/device/push": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers (or reactivates) the device's push token for the authenticated user. Requires a bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register push token",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes the given refresh token. Requires a bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Validates a refresh token, rotates it (the old one is revoked), and returns a new access + refresh pair. 401 if expired/revoked/unknown.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh tokens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/entities": {
            "get": {
                "description": "Cross-sport text-only directory of players and teams for home-page search.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get universal entity autofill directory",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns serving readiness; 503 when the database is unreachable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health/cache": {
            "get": {
                "description": "Returns in-memory cache statistics (active keys, expired keys).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Cache health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health/db": {
            "get": {
                "description": "Verifies Postgres connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Database health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/{sport}/autofill": {
            "get": {
                "description": "The sport-scoped autofill/search payload for existing consumers. Use /api/v1/entities for universal home search.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the legacy sport autofill/search payload",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/health": {
            "get": {
                "description": "Returns sport data freshness and counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get sport health page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leaderboard": {
            "get": {
                "description": "Positionless rating board (z-score engine). entity_type=player (default) or team. Composite + Sigil in one payload.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get rating leaderboard",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Board type: player (default) or team",
                        "name": "entity_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Board: composite (default), sigil, or a sigil label (e.g. Sacks)",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Season year (defaults to the latest rated season)",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a position (player boards only)",
                        "name": "position",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter to a league (football)",
                        "name": "league_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max rows (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leaderboard/news": {
            "get": {
                "description": "Sport-wide board of the hottest model narratives with source freshness and trajectory markers.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "News leaderboard",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter: player or team (default both)",
                        "name": "entity_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "News scope: current_week, last_week, two_weeks_ago, three_weeks_ago, last_month",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max rows (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leaderboard/sigil": {
            "get": {
                "description": "Sport-wide board of entities ranked by their latest Sigil crown score (1-100), the holistic Rating+Vibe synthesis. With the Sigil blurb + previous_score delta.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Sigil leaderboard",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter: player or team (default both)",
                        "name": "entity_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max rows (default 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Season year (default current)",
                        "name": "season",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leaderboard/transfers": {
            "get": {
                "description": "Sport-wide board of the hottest model-vetted transfer rumors, ranked by heat (0-100).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Transfers leaderboard",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max rows (default 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Transfer scope: current_week, last_week, two_weeks_ago, three_weeks_ago, last_month",
                        "name": "scope",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leaderboard/trending": {
            "get": {
                "description": "Entities ranked by their recent trajectory slope (risers). metric=vibe (default) or rating.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Trending leaderboard (risers)",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Trajectory: vibe (default) or rating",
                        "name": "metric",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter: player or team (default both)",
                        "name": "entity_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max rows (default 30)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leaderboard/vibes": {
            "get": {
                "description": "Sport-wide board of entities ranked by latest vibe sentiment (1-100). With the Vibe felt-read blurb.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Vibes leaderboard",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter: player or team (default both)",
                        "name": "entity_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max rows (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leagues/{leagueId}/health": {
            "get": {
                "description": "Returns sport data freshness and counts for a specific league.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get league health page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID",
                        "name": "leagueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leagues/{leagueId}/meta": {
            "get": {
                "description": "Returns metadata and search payload for a specific league.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get league meta page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID",
                        "name": "leagueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leagues/{leagueId}/team/{id}/results": {
            "get": {
                "description": "League-scoped variant of GetTeamResults — leagueId comes from the URL path. Identical payload.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get league team season results",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID",
                        "name": "leagueId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leagues/{leagueId}/{entityType}/{id}/momentum": {
            "get": {
                "description": "League-scoped momentum payload. Mirrors GetTrendsPage with leagueId taken from the URL path.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get league momentum page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID",
                        "name": "leagueId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/meta": {
            "get": {
                "description": "Returns the legacy complete metadata and search payload for a sport.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get legacy sport metadata/search payload",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/team/{id}/results": {
            "get": {
                "description": "Returns the team's list of finalized fixtures (status completed/seeded) for a season, framed from the team's perspective with opponent identity and W/L/D.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get team season results",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/team/{id}/roster": {
            "get": {
                "description": "Players on the team's season roster with season Composite/Sigil (+ ranks + sigil label), ordered by the Composite+Sigil sum. Player names link to the player profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get team roster (rating)",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/meta": {
            "get": {
                "description": "The entity's identity for the page header: name, image, physicals, current team/club, position, tier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get per-entity identity metadata",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/momentum": {
            "get": {
                "description": "Returns the entity's last-3 event averages and peer-cohort season averages so the frontend can derive recent direction relative to peers. Raw values only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get momentum (rating + vibe trajectory)",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/news": {
            "get": {
                "description": "The entity's latest precomputed narratives (hottest first) ranked by per-narrative impact.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the entity news narratives",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "News scope: current_week, last_week, two_weeks_ago, three_weeks_ago, last_month",
                        "name": "scope",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/rating": {
            "get": {
                "description": "The entity's positionless magnitude score, divined defining strength, and precomputed stat-identity blurb.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the entity rating (magnitude + strength + identity blurb)",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/sigil": {
            "get": {
                "description": "The entity's holistic Sigil synthesis — score (1-100) + blurb fusing Rating + Vibe + Momentum — plus a bounded history.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the entity Sigil (crown synthesis)",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year (default current)",
                        "name": "season",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/stats": {
            "get": {
                "description": "The entity's season Composite rating (breakdown, modes, fantasy, scoped ranks) + available seasons.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the entity season rating",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/transfers": {
            "get": {
                "description": "The entity's vetted transfer/trade rumors ranked by deterministic heat (team→players, player→clubs).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the entity transfer rumors",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Transfer scope: current_week, last_week, two_weeks_ago, three_weeks_ago, last_month",
                        "name": "scope",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "respond.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string"
                        },
                        "detail": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Scoracle Data API",
	Description:      "Unified Scoracle API serving sport data pages, derived products (narratives, transfer heat, Vibe, Sigil — precomputed by the Rust cognition layer), health checks, and operational endpoints.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
