// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Scoracle"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns API name, version, status, and available optimizations.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "API root info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/device": {
            "post": {
                "description": "Creates a new anonymous user and returns an access + refresh token pair. First launch only; later launches use /auth/refresh.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register device (anonymous)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/device/push": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers (or reactivates) the device's push token for the authenticated user. Requires a bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register push token",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes the given refresh token. Requires a bearer token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Validates a refresh token, rotates it (the old one is revoked), and returns a new access + refresh pair. 401 if expired/revoked/unknown.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh tokens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns basic health status and timestamp.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health/cache": {
            "get": {
                "description": "Returns in-memory cache statistics (active keys, expired keys).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Cache health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health/db": {
            "get": {
                "description": "Verifies Postgres connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Database health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/news/status": {
            "get": {
                "description": "Returns configuration state for the Google News RSS source.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "News service status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/news/{entityType}/{entityID}": {
            "get": {
                "description": "Returns news articles about a player or team from Google News RSS. Supports time-window escalation and strict name matching.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Get entity news",
                "parameters": [
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "entityID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "NBA",
                            "NFL",
                            "FOOTBALL"
                        ],
                        "type": "string",
                        "description": "Sport identifier",
                        "name": "sport",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Team name for player context",
                        "name": "team",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max articles (1-50, default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/twitter/status": {
            "get": {
                "description": "Returns per-sport cache state, since_id, last_fetched_at, and bearer-token configuration.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "twitter"
                ],
                "summary": "Twitter service status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/{sport}/autofill": {
            "get": {
                "description": "The sport's autofill + search payload for frontend local hydration — the dedicated home for what /meta historically served.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the sport autofill/search index",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/health": {
            "get": {
                "description": "Returns sport data freshness and counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get sport health page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leaderboard": {
            "get": {
                "description": "Positionless rating board (z-score engine). entity_type=player (default) or team. Composite + Sigil in one payload.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get rating leaderboard",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Board type: player (default) or team",
                        "name": "entity_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Board: composite (default), sigil, or a sigil label (e.g. Sacks)",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Season year (defaults to the latest rated season)",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a position (player boards only)",
                        "name": "position",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter to a league (football)",
                        "name": "league_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max rows (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leaderboard/news": {
            "get": {
                "description": "Sport-wide board of the most-mentioned entities in the news corpus over the rolling window.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "News leaderboard",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter: player or team (default both)",
                        "name": "entity_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Rolling window in days (default 30)",
                        "name": "days",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max rows (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leaderboard/transfers": {
            "get": {
                "description": "Sport-wide board of the hottest Gemma-vetted transfer rumors, ranked by heat (0-100).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Transfers leaderboard",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max rows (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leaderboard/vibes": {
            "get": {
                "description": "Sport-wide board of entities ranked by latest vibe sentiment (1-100). Enriched sibling of /vibe/hottest.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Vibes leaderboard",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter: player or team (default both)",
                        "name": "entity_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max rows (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leagues/{leagueId}/health": {
            "get": {
                "description": "Returns sport data freshness and counts for a specific league.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get league health page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID",
                        "name": "leagueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leagues/{leagueId}/meta": {
            "get": {
                "description": "Returns metadata and search payload for a specific league.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get league meta page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID",
                        "name": "leagueId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leagues/{leagueId}/team/{id}/results": {
            "get": {
                "description": "League-scoped variant of GetTeamResults — leagueId comes from the URL path. Identical payload.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get league team season results",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID",
                        "name": "leagueId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leagues/{leagueId}/{entityType}/{id}": {
            "get": {
                "description": "Returns the sport profile payload scoped to a specific league.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get league profile page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID",
                        "name": "leagueId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/leagues/{leagueId}/{entityType}/{id}/trends": {
            "get": {
                "description": "League-scoped trends payload. Mirrors GetTrendsPage with leagueId taken from the URL path.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get league trends page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID",
                        "name": "leagueId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/meta": {
            "get": {
                "description": "Returns complete metadata and search payload for a sport.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get meta page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/team/{id}/results": {
            "get": {
                "description": "Returns the team's list of finalized fixtures (status completed/seeded) for a season, framed from the team's perspective with opponent identity and W/L/D.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get team season results",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/team/{id}/roster": {
            "get": {
                "description": "Players on the team's season roster with season Composite/Sigil (+ ranks + sigil label), ordered by the Composite+Sigil sum. Player names link to the player profile.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get team roster (rating)",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/twitter/feed": {
            "get": {
                "description": "Returns cached tweets from the sport's curated X List. Refreshes on demand when older than the TTL; concurrent refreshes are coalesced via singleflight.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "twitter"
                ],
                "summary": "Sport tweet feed",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max tweets (1-100, default 25)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/twitter/{entityType}/{id}": {
            "get": {
                "description": "Returns cached tweets mentioning the given player or team. Matching uses the shared search_aliases logic.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "twitter"
                ],
                "summary": "Entity tweet feed",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max tweets (1-100, default 25)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}": {
            "get": {
                "description": "Returns the sport profile payload for an entity type and ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get profile page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/meta": {
            "get": {
                "description": "The entity's identity for the page header: name, image, physicals, current team/club, position, tier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get per-entity identity metadata",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/news": {
            "get": {
                "description": "The entity's latest Gemma narratives (hottest first) ranked by per-narrative impact.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the entity news narratives",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/sigil": {
            "get": {
                "description": "The entity's sigil rating, the sigil datapoints, and the Gemma stat commentary.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the entity sigil + commentary",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/stats": {
            "get": {
                "description": "The entity's season Composite rating (breakdown, modes, fantasy, scoped ranks) + available seasons.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the entity season rating",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/transfers": {
            "get": {
                "description": "The entity's vetted transfer/trade rumors ranked by deterministic heat (team→players, player→clubs).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the entity transfer rumors",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/trends": {
            "get": {
                "description": "Returns the entity's last-3 event averages and peer-cohort season averages so the frontend can derive recent direction relative to peers. Raw values only.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get trends page",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID filter",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{sport}/{entityType}/{id}/vibes": {
            "get": {
                "description": "The entity's current vibe sentiment (1-100) plus a bounded history for the trend sparkline.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "data"
                ],
                "summary": "Get the entity vibe sentiment",
                "parameters": [
                    {
                        "enum": [
                            "nba",
                            "nfl",
                            "football"
                        ],
                        "type": "string",
                        "description": "Sport",
                        "name": "sport",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/respond.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "respond.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string"
                        },
                        "detail": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Scoracle Data API",
	Description:      "Unified Scoracle API serving sport data pages, news, journalist tweets, health checks, and operational endpoints.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
