// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Scoracle"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns API name, version, status, and available optimizations.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "API root info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/autofill_databases": {
            "get": {
                "description": "Returns the complete entity list (players + teams) for a sport, used for frontend search/autofill. Served from mv_autofill_entities materialized view.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bootstrap"
                ],
                "summary": "Get autofill database",
                "parameters": [
                    {
                        "enum": [
                            "NBA",
                            "NFL",
                            "FOOTBALL"
                        ],
                        "type": "string",
                        "description": "Sport identifier",
                        "name": "sport",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns basic health status and timestamp.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health/cache": {
            "get": {
                "description": "Returns in-memory cache statistics (active keys, expired keys).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Cache health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health/db": {
            "get": {
                "description": "Verifies Postgres connectivity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Database health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/news/status": {
            "get": {
                "description": "Returns configuration state for RSS and NewsAPI sources.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "News service status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/news/{entityType}/{entityID}": {
            "get": {
                "description": "Returns news articles about a player or team from Google News RSS (primary) or NewsAPI (fallback). Supports time-window escalation and strict name matching.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "news"
                ],
                "summary": "Get entity news",
                "parameters": [
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "entityID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "NBA",
                            "NFL",
                            "FOOTBALL"
                        ],
                        "type": "string",
                        "description": "Sport identifier",
                        "name": "sport",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Team name for player context",
                        "name": "team",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max articles (1-50, default 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "rss",
                            "api",
                            "both"
                        ],
                        "type": "string",
                        "default": "rss",
                        "description": "News source preference",
                        "name": "source",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/profile/{entityType}/{entityID}": {
            "get": {
                "description": "Returns a complete player or team profile with bio, current team, and summary stats. Response is raw JSON from Postgres api_player_profile/api_team_profile functions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profiles"
                ],
                "summary": "Get entity profile",
                "parameters": [
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "entityID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "NBA",
                            "NFL",
                            "FOOTBALL"
                        ],
                        "type": "string",
                        "description": "Sport identifier",
                        "name": "sport",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/definitions": {
            "get": {
                "description": "Returns canonical stat definitions (names, display labels, categories) for a sport.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get stat definitions",
                "parameters": [
                    {
                        "enum": [
                            "NBA",
                            "NFL",
                            "FOOTBALL"
                        ],
                        "type": "string",
                        "description": "Sport identifier",
                        "name": "sport",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/{entityType}/{entityID}": {
            "get": {
                "description": "Returns stats and percentiles for a player or team for a given season. Response is raw JSON from Postgres api_entity_stats function.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get entity stats",
                "parameters": [
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "entityID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "NBA",
                            "NFL",
                            "FOOTBALL"
                        ],
                        "type": "string",
                        "description": "Sport identifier",
                        "name": "sport",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Season year (defaults to current)",
                        "name": "season",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "League ID (for FOOTBALL)",
                        "name": "league_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/{entityType}/{entityID}/seasons": {
            "get": {
                "description": "Returns a list of seasons that have stats for an entity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get available seasons",
                "parameters": [
                    {
                        "enum": [
                            "player",
                            "team"
                        ],
                        "type": "string",
                        "description": "Entity type",
                        "name": "entityType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entity ID",
                        "name": "entityID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "NBA",
                            "NFL",
                            "FOOTBALL"
                        ],
                        "type": "string",
                        "description": "Sport identifier",
                        "name": "sport",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/twitter/journalist-feed": {
            "get": {
                "description": "Searches the cached journalist X List feed for entity mentions. Full feed is fetched once and cached for 1 hour; searches filter the cache client-side.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "twitter"
                ],
                "summary": "Search journalist feed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query (1-200 chars)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "NBA",
                            "NFL",
                            "FOOTBALL"
                        ],
                        "type": "string",
                        "description": "Sport context (metadata only)",
                        "name": "sport",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max tweets (1-50, default 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/twitter/status": {
            "get": {
                "description": "Returns Twitter API configuration state, list ID, cache TTL, and rate limit info.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "twitter"
                ],
                "summary": "Twitter service status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_albapepper_scoracle-data_internal_api_respond.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string"
                        },
                        "detail": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Scoracle Data API",
	Description:      "Sports analytics API serving player/team profiles, stats, percentiles, news, and journalist tweets. All data-heavy responses are JSON-passthrough from Postgres functions.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
